import type * as Monaco from "monaco-editor";
import { createRange } from "./utils.js";

export function registerPythonIntelliSense(monaco: typeof Monaco): Monaco.IDisposable {
  const snippetRule = monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet;

  return monaco.languages.registerCompletionItemProvider("python", {
    provideCompletionItems(model, position) {
      const range = createRange(monaco, model, position);

      const keywords = [
        "False",
        "None",
        "True",
        "and",
        "as",
        "assert",
        "async",
        "await",
        "break",
        "class",
        "continue",
        "def",
        "del",
        "elif",
        "else",
        "except",
        "finally",
        "for",
        "from",
        "global",
        "if",
        "import",
        "in",
        "is",
        "lambda",
        "nonlocal",
        "not",
        "or",
        "pass",
        "raise",
        "return",
        "try",
        "while",
        "with",
        "yield",
      ];

      const builtins = [
        "abs",
        "all",
        "any",
        "bool",
        "dict",
        "enumerate",
        "float",
        "input",
        "int",
        "isinstance",
        "len",
        "list",
        "map",
        "max",
        "min",
        "open",
        "print",
        "range",
        "reversed",
        "round",
        "set",
        "sorted",
        "str",
        "sum",
        "tuple",
        "type",
        "zip",
      ];

      const suggestions: Monaco.languages.CompletionItem[] = [
        ...keywords.map((keyword) => ({
          label: keyword,
          kind: monaco.languages.CompletionItemKind.Keyword,
          insertText: keyword,
          documentation: `Python keyword: ${keyword}`,
          range,
        })),
        ...builtins.map((builtin) => ({
          label: builtin,
          kind: monaco.languages.CompletionItemKind.Function,
          insertText: `${builtin}($1)`,
          insertTextRules: snippetRule,
          documentation: `Python built-in function: ${builtin}`,
          range,
        })),
        {
          label: "def",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "def ${1:function_name}(${2:args}):\n\t${3:pass}",
          insertTextRules: snippetRule,
          documentation: "Function definition.",
          range,
        },
        {
          label: "class",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText:
            "class ${1:ClassName}:\n\tdef __init__(self${2:, args}):\n\t\t${3:pass}",
          insertTextRules: snippetRule,
          documentation: "Class definition with an initializer.",
          range,
        },
        {
          label: "import",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "import ${1:module_name}",
          insertTextRules: snippetRule,
          documentation: "Import a module.",
          range,
        },
        {
          label: "from import",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "from ${1:module_name} import ${2:name}",
          insertTextRules: snippetRule,
          documentation: "Import names from a module.",
          range,
        },
        {
          label: "if",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "if ${1:condition}:\n\t${2:pass}",
          insertTextRules: snippetRule,
          documentation: "If statement.",
          range,
        },
        {
          label: "if else",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "if ${1:condition}:\n\t${2:pass}\nelse:\n\t${3:pass}",
          insertTextRules: snippetRule,
          documentation: "If/else block.",
          range,
        },
        {
          label: "for",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "for ${1:item} in ${2:items}:\n\t${3:pass}",
          insertTextRules: snippetRule,
          documentation: "For loop.",
          range,
        },
        {
          label: "while",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "while ${1:condition}:\n\t${2:pass}",
          insertTextRules: snippetRule,
          documentation: "While loop.",
          range,
        },
        {
          label: "try except",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "try:\n\t${1:pass}\nexcept ${2:Exception} as ${3:error}:\n\t${4:pass}",
          insertTextRules: snippetRule,
          documentation: "Try/except block.",
          range,
        },
        {
          label: "with open",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "with open(${1:path}, ${2:\"r\"}) as ${3:file}:\n\t${4:pass}",
          insertTextRules: snippetRule,
          documentation: "Open a file with a context manager.",
          range,
        },
        {
          label: "if __name__ == '__main__':",
          kind: monaco.languages.CompletionItemKind.Snippet,
          insertText: "if __name__ == '__main__':\n\t${1:main()}",
          insertTextRules: snippetRule,
          documentation: "Boilerplate for executable script entry point.",
          range,
        },
      ];

      return { suggestions };
    },
  });
}
